version: '3.0'

services:
  frontend:
    container_name: frontend
    build:
      context: .
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    restart: on-failure
