version: '3.0'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  pgdata:
